name: Nightly build WinCE

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: setup_cegcc
      run: |
        wget https://github.com/brain-hackers/cegcc-build/releases/download/2022-10-26-225811/cegcc-x86_64-2022-10-26-225811.zip -O cegcc.zip
        unzip cegcc.zip -d /opt
        echo /opt/cegcc/bin >> $GITHUB_PATH

    - name: download_dependencies
      run: |
        wget https://master.dl.sourceforge.net/project/cegcc/ported%20packages/freetype-2.3.7/freetype-2.3.7-dev.tar.bz2 -O freetype.tar.bz2
        wget https://master.dl.sourceforge.net/project/cegcc/ported%20packages/libpng-1.2.33/libpng-1.2.33-dev.tar.bz2 -O libpng.tar.bz2
        wget https://master.dl.sourceforge.net/project/cegcc/ported%20packages/zlib-1.2.3/zlib-1.2.3-dev.tar.bz2 -O zlib.tar.bz2
        wget https://github.com/RasPython3/bzip2-ce/releases/download/2026-03-27/bzip2.zip -O bzip2.zip
        tar -jxvf freetype.tar.bz2
        tar -jxvf libpng.tar.bz2
        tar -jxvf zlib.tar.bz2
        unzip bzip2.zip -d bzip2
        rm *.bz2 *.zip
        mv freetype* freetype
        mv libpng* libpng
        mv zlib* zlib

    - name: Configure Simutrans Build
      run: |
        autoconf
        LDFLAGS="-L$PWD/freetype/lib -L$PWD/libpng/lib -L$PWD/zlib/lib -L$PWD/bzip2/lib" ./configure --host arm-mingw32ce
        echo "MINGW_PACKAGE_PREFIX := arm-mingw32ce" >> config.default
        echo "LDFLAGS += -static -L$PWD/freetype/lib -L$PWD/libpng/lib -L$PWD/zlib/lib -L$PWD/bzip2/lib" >> config.default
        echo "CFLAGS += -DUSE_OWN_PAKINSTALL -DIGNORE_LANG_CASE -DSCREENSHOT_BMP -DUINT64_MAX=UINT_MAX -DINT32_MAX=INT_MAX -DINT64_C\(x\)=\(\(int64_t\)x\) -DPRId64=\\\"d\\\" -I$PWD/freetype/include/freetype2 -I$PWD/libpng/include/libpng12 -I$PWD/zlib/include -I$PWD/bzip2/include" >> config.default
        echo "CC := arm-mingw32ce-gcc" >> config.default
        echo "CXX := arm-mingw32ce-g++" >> config.default
        echo "LD := arm-mingw32ce-ld" >> config.default
        echo "WINDRES := arm-mingw32ce-windres" >> config.default
        echo "STATIC := 0" >> config.default
        echo "GIT_HASH := 1" >> config.default
        echo "OPTIMISE_LEVEL := s" >> config.default

    - name: Build Simutrans
      run: |
        make -j$(nproc)

    - name: Bundle pak64
      run: |
        PAKURL=`cat tools/get_pak.sh  | grep -E "^\s*\".*/pak64/" | sed 's/^.*"\(.*\)".*$/\1/g'`
        wget $PAKURL -O pak.zip
        unzip pak.zip -d .
        wget https://sourceforge.net/p/simutrans/code/HEAD/tree/pak64/licence.txt?format=raw -O simutrans/licence-pak64.txt

    - name: Distribute
      run: |
        cp tools/get_pak.sh tools/get_pak.ps1 simutrans/
        ./tools/distribute.sh -no-rev
        mv simuwin-*.zip simuwce-arm-nightly.zip
        zip -u simuwce-arm-nightly.zip simutrans/get_pak.sh simutrans/get_pak.ps1 `find simutrans -type f "(" -name "*.bdf" -o -name "*.fnt" ")"`

    - name: Distribute for SHARP Brain
      run: |
        cp simuwce-arm-nightly.zip simu-brain-nightly.zip
        cp sim.exe simutrans/AppMain.exe
        touch simutrans/index.din
        cp simutrans/config/simuconf.tab simutrans/config/simuconf.tab.org
        cat simutrans/config/simuconf.tab.org |
          sed -E 's/^(max_route_steps\s*=\s*).*$/\1100000/g' |
          sed -E 's/^(saveformat\s*=\s*).*$/\1xml/g' |
          sed -E 's/^(autosaveformat\s*=\s*).*$/\1binary/g' > simutrans/config/simuconf.tab
        zip -d simu-brain-nightly.zip simutrans/simutrans.exe
        zip -u simu-brain-nightly.zip simutrans/AppMain.exe simutrans/index.din simutrans/config/simuconf.tab

    - name: Update binaries of Nightly Release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: simuwce-arm-nightly.zip
        asset_name: simuwce-arm-nightly.zip
        tag: Nightly
        overwrite: true

    - name: Update binaries of Nightly Release for SHARP Brain
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: simu-brain-nightly.zip
        asset_name: simu-brain-nightly.zip
        tag: Nightly
        overwrite: true
